[package]
name = "share"
version = "0.1.0"
authors = ["Alexander Mielczarek <almielczarek@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "*"
gotham_derive = "*"
tera = "0.11"
mime = "0.3"
serde = "1"
serde_derive = "1"
hyper = "*"
