[package]
name = "pub"
version = "0.1.0"
authors = ["Alexander Mielczarek <almielczarek@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "0.3"
gotham_derive = "0.3"
tera = "0.11"
mime = "0.3"
serde = "1"
serde_derive = "1"
hyper = "0.12"
